services:
  - type: web
    name: sk-jabein-portfolio
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
